services:
   appbundle.admin.category:
       class: AppBundle\Admin\NoteAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: notes, label: "Notes" }
       arguments:
           - ~
           - AppBundle\Entity\Note
           - 'AppBundle:NoteAdmin'
           
